# Generated by Django 3.1.2 on 2020-10-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
